### Python for Time Series Data Analysis

### Section 1: Introduction:
        * 1. Course Overview - PLEASE DO NOT SKIP THIS LECTURE
        * Quiz 1: Course Overview Check 
        * 2. Course Curriculum Overview
        * 3. FAQ - Frequently Asked Questions
        
### Section 2: Course Set Up and Install:
        * 4. Installing Anaconda Python Distribution and Jupyter
### Section 3: NumPy
        * 5. NumPy Section Overview
        * 6. NumPy Arrays - Part One

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mylist = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mymatrix=np.array(mylist)

In [11]:
mymatrix.shape

(3, 3)

In [14]:
mynewmatrix = np.array(mylist)

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [18]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [19]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Section 3: NumPy
        * 5. NumPy Section Overview
        * 6. NumPy Arrays - Part One
        * 7. NumPy Arrays - Part Two

In [25]:
np.random.rand(5,5)

array([[0.40041976, 0.00200246, 0.25466695, 0.59292129, 0.33228824],
       [0.40919902, 0.49483235, 0.53426483, 0.86497923, 0.6682589 ],
       [0.95372552, 0.83098829, 0.58956734, 0.58531906, 0.14198696],
       [0.12963804, 0.22197514, 0.85798187, 0.48117215, 0.34884858],
       [0.24455252, 0.16289497, 0.32119406, 0.88775387, 0.3996983 ]])

In [27]:
np.random.randn(10)

array([ 6.59986216e-01, -4.88101915e-01, -5.49834446e-01, -7.00697757e-04,
       -1.66929774e+00, -1.91415924e-01,  1.10211024e+00,  7.92088828e-01,
       -2.42746822e-01, -5.41131572e-01])

In [28]:
#np.random.normal

In [30]:
np.random.randint(1,100,10)

array([62, 38, 25, 54, 20, 51, 75, 42, 20, 47])

In [34]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [35]:
np.random.rand(4)

array([0.58120733, 0.14267862, 0.94591918, 0.33999059])

In [36]:
np.random.rand(4)

array([0.62043546, 0.45295964, 0.23976742, 0.03450459])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)

In [41]:
ranarr

array([17,  4, 41, 12, 49,  1,  8, 20, 27, 29])

In [42]:
arr.shape

(25,)

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.max()

49

In [45]:
ranarr.min()

1

In [47]:
ranarr

array([17,  4, 41, 12, 49,  1,  8, 20, 27, 29])

In [48]:
ranarr.argmax()

4

In [49]:
ranarr.argmin()

5

In [50]:
ranarr.dtype

dtype('int32')

### Section 3: NumPy
        * 5. NumPy Section Overview
        * 6. NumPy Arrays - Part One
        * 7. NumPy Arrays - Part Two
        * 8. NumPy Indexing and Selection

In [52]:
arr_2d = np.array([[5,10,15], [20, 25,30], [35,40,45]])

In [53]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d.shape

(3, 3)

In [56]:
arr_2d[1][1]

25

In [57]:
arr_2d[2,2]

45

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [61]:
arr = np.arange(1,11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
bool_arr = arr > 4

In [65]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### Section 3: NumPy
        * 5. NumPy Section Overview
        * 6. NumPy Arrays - Part One
        * 7. NumPy Arrays - Part Two
        * 8. NumPy Indexing and Selection
        * 9. NumPy Operations

In [68]:
arr = np.arange(0,10)

In [69]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [71]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [73]:
(arr + 2)/100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11])

In [74]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
1/arr

<ipython-input-77-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [78]:
arr/arr

<ipython-input-78-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [80]:
np.log(arr)

<ipython-input-80-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [82]:
arr.sum()

45

In [83]:
arr.mean()

4.5

In [84]:
arr.max()

9

In [85]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [86]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
arr_2d.shape

(3, 4)

In [90]:
arr_2d.sum()

78

In [92]:
#give me the sum, across the rows
arr_2d.sum(axis=0)
#sum of the value in colums

array([15, 18, 21, 24])

In [93]:
arr_2d.sum(axis=1)

array([10, 26, 42])

### Section 3: NumPy
        * 5. NumPy Section Overview
        * 6. NumPy Arrays - Part One
        * 7. NumPy Arrays - Part Two
        * 8. NumPy Indexing and Selection
        * 9. NumPy Operations
        * 10. NumPy Exercises
        * 11. NumPy Exercises Solutions

In [1]:
#Exercises

### Section 4: Pandas Overview
        * 12. Introduction to Pandas
        * 13. Series
        * 14. DataFrames - Part One
        * 15. DataFrames - Part Two
        * 16. Missing Data with Pandas
        * 17. Group By Operations
        * 18. Common Operations
        * 19. Data Input and Output
        * 20. Pandas Exercises
        * 21. Pandas Exercises Solutions

### Section 5: Data Visualization with Pandas
        * 22
        * 23.
        * 24. 
        * 25. 
        * 26. 

### Section 6: Time Series with Pandas
        * 27. 
        * 28. 
        * 29. 
        * 30. 
        * 31. 
        * 32
        * 33
        * 34
        * 35
        * 36
        * 37
        * 38

### Section 7: Time Series Analysis with Statsmodels
        * 39. 
        * 40. 
        * 41. 
        * 42. 
        * 43. 
        * 44
        * 45
        * 46
        * 47
        * 48

### Section 8: General Forecasting Models
        * 
        *  
        * 
        *  
        *  
        * 
        * 
        * 
        * 
        * 

### Section 9: Deep Learning for Time Series Forecasting
        * 
        *  
        * 
        *  
        *  
        * 
        * 
        * 
        * 
        * 

### Section 
        * 
        *  
        * 
        *  
        *  
        * 
        * 
        * 
        * 
        * 

### Section 
        * 
        *  
        * 
        *  
        *  
        * 
        * 
        * 
        * 
        * 

### Section 
        * 
        *  
        * 
        *  
        *  
        * 
        * 
        * 
        * 
        * 